language: java
sudo: required

jdk:
  - oraclejdk8

before_install:
  - wget -O - https://github.com/jphp-compiler/jphp/releases/download/jppm-0.3.0/jppm-setup-0.3.0.sh | bash

script:
 - jppm install
 - jppm test